services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      NODE_ENV: development
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digital_pantry
    depends_on:
      - db
    volumes:
      - ./db:/app/migrations
      - ./src:/app/src

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      NODE_ENV: development
      PORT: 8080
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digital_pantry
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: