services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - 8080:8080
    env_file:
      .env
    depends_on:
      - db
    volumes:
      - ./db:/app/migrations
      - ./src:/app/src

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      .env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: